2019-06-05 14:47:18,291 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 14:48:36,658 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 14:52:07,323 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 14:52:17,457 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 14:54:54,876 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 14:55:01,263 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 14:55:57,213 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:01:04,774 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:01:11,408 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 15:03:24,618 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:03:58,878 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:04:07,308 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 15:05:09,164 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:05:13,493 ERROR: Exception on /edit_profile [POST] [in c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\1\desktop\flasker\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\1\Desktop\flasker\app\routes.py", line 85, in edit_profile
    current_user.username = form.username.date
AttributeError: 'StringField' object has no attribute 'date'
2019-06-05 15:06:15,654 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
2019-06-05 15:07:45,454 INFO: Microblog startup [in C:\Users\1\Desktop\flasker\app\__init__.py:43]
